baseURL = "https://engineering-ai.space/"
title = "Engineering AI"
theme = "hugo-theme-tokyo-terminal"
languageCode = "en-us"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1

[pagination]
  pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  prompt = "guest@engineering-ai:~$"
  contentTypeName = "posts"
  readingTime = true
  Toc = true

  [params.dashboard]
    enabled = true
    ascii_art = """
███████╗███╗   ██╗ ██████╗ ██╗███╗   ██╗███████╗███████╗██████╗ ██╗███╗   ██╗ ██████╗      █████╗ ██╗
██╔════╝████╗  ██║██╔════╝ ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║████╗  ██║██╔════╝     ██╔══██╗██║
█████╗  ██╔██╗ ██║██║  ███╗██║██╔██╗ ██║█████╗  █████╗  ██████╔╝██║██╔██╗ ██║██║  ███╗    ███████║██║
██╔══╝  ██║╚██╗██║██║   ██║██║██║╚██╗██║██╔══╝  ██╔══╝  ██╔══██╗██║██║╚██╗██║██║   ██║    ██╔══██║██║
███████╗██║ ╚████║╚██████╔╝██║██║ ╚████║███████╗███████╗██║  ██║██║██║ ╚████║╚██████╔╝    ██║  ██║██║
╚══════╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝     ╚═╝  ╚═╝╚═╝
"""
    ascii_color = "#bb9af7"
    title = "Engineering AI"
    subtitle = "ML & AI Research Company"
    hint = "Press the highlighted keys to navigate."

  [[params.social]]
    name = "github"
    url = "https://github.com/project-engineering-ai"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    [menu.main.params]
      shortcut = "a"
      icon = ""
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    [menu.main.params]
      shortcut = "s"
      icon = ""
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    [menu.main.params]
      shortcut = "b"
      icon = ""
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    [menu.main.params]
      shortcut = "c"
      icon = ""
